# Harmony Jekyll theme general configurations 

# Base URL
baseurl: ''

# Site live URL
url: http://gracece.com

# Localhost 
# url: http://127.0.0.1:4000  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Gracece's Blog
  # Little description about your site
  description:  生命不息，折腾不止。
  meta_description: 折腾不止
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Lingyuan Guo
    email: guolyuan@gmail.com
    url: http://gracece.com

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-37030678-2
  disqus_shortname: gracece

  # Profile links, leave blank to ignore
  social: 
    github: gracece 
    twitter: guolyuan
    facebook: 
    gplus: 
    dribble: 
    pinterest: 
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings 
markdown:    kramdown
highlighter: pygments # this is how you put pygments config in jekyll 2.0 instead of pygments: true

# Permalinks
permalink: /:year/:month/:title 
#permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
